#!/bin/zsh

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# reset
rm ~/.config/herbstluftwm/*.log
hc keyunbind --all
pkill xautolock

#variables
Mod=Mod4     # Use the super key as the main modifier

######### MACHINE SPECIFIC SETUP #########
### Atlantis PC-specific setup ###
if [[ "$HOST" == "atlantispc" ]]; then
    /usr/bin/xrandr --output DVI-D-1 --right-of HDMI-1
    #hc detect_monitors
    hc set swap_monitors_to_get_tag 0
#    hc set_monitors 3840x1080+0+0
#    hc keybind $Mod-o spawn /bin/bash -c "/home/sheppy/.config/i3lock/piclock.sh && sudo s2disk"
fi

if [[ "$HOST" == "atlantisV2" ]]; then
    /usr/bin/xrandr --output DP-1 --right-of HDMI-0
fi

### Atlantislaptop specific setup ###
if [[ "$HOST" == "atlantislaptop" ]]; then
    hc keybind XF86MonBrightnessUp spawn /bin/bash -c 'tee /sys/class/backlight/intel_backlight/brightness <<< "$(expr $(cat /sys/class/backlight/intel_backlight/brightness) + 5)"' 
    hc keybind XF86MonBrightnessDown spawn /bin/bash -c 'tee /sys/class/backlight/intel_backlight/brightness <<< "$(expr $(cat /sys/class/backlight/intel_backlight/brightness) - 5)"'
fi


######### GENERAL SETUP #########
hc spawn ~/.config/herbstluftwm/hl_status_deamon.py

# keybindings
hc keybind $Mod-Shift-q spawn /bin/bash -c "pkill hl_status_deamo & pkill ssh-agent & ~/.config/other/notify_logout.sh  &herbstclient quit"
if [[ $HOST =~ atlantis* ]]; then
    hc keybind $Mod-Shift-p spawn sudo /sbin/poweroff
fi
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close

#spawn shit
hc keybind $Mod-Return spawn urxvt 
hc keybind $Mod-y spawn urxvt #easier to press with one hand
hc keybind $Mod-Shift-Return spawn ~/.config/herbstluftwm/hl_start_urxvt_cwd.py
hc keybind $Mod-i spawn "/usr/bin/chromium"

if [[ $HOST =~ atlantis* ]]; then
    hc keybind $Mod-l spawn i3lock -i ~/.config/i3lock/bg_new.png -t
else
    hc keybind $Mod-l spawn xlock -fg green
    hc keybind $Mod-Shift-x spawn xlock -mode blank -geometry 1x1
    hc keybind $Mod-x spawn xlock -mode blank -geometry 1x1
fi

hc keybind $Mod-p spawn pavucontrol
hc keybind $Mod-Shift-l spawn libreoffice
hc keybind $Mod-t spawn /bin/bash -c "LC_ALL=en_DK.utf8 && export LC_ALL && thunderbird"
hc keybind $Mod-Shift-j spawn urxvt -e ssh sheppy@irc-new.atlantishq.de -t 'tmux a -d'
hc keybind $Mod-e spawn rofi -combi-mode window,run -show combi -modi combi
hc keybind $Mod-Shift-e spawn rofi -show run
hc keybind $Mod-u       spawn /usr/bin/pulseaudio -k

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-a     focus left
hc keybind $Mod-s     focus down
hc keybind $Mod-w     focus up
hc keybind $Mod-d     focus right

hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-a     shift left
hc keybind $Mod-Shift-s     shift down
hc keybind $Mod-Shift-w     shift up
hc keybind $Mod-Shift-d     shift right

hc keybind $Mod-h       split   bottom  0.5
hc keybind $Mod-v       split   right   0.5

# resizing frames
resizestep=0.05
small_resize=0.001
hc keybind $Mod-Control-a       resize left +$small_resize
hc keybind $Mod-Control-s       resize down +$small_resize
hc keybind $Mod-Control-w       resize up +$small_resize
hc keybind $Mod-Control-d       resize right +$small_resize
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
hc rename default "1" || true
hc add "2"
hc add "3"
hc add "4"
hc add "5"
hc add "6"
hc add "7"
hc add "8"
hc add "9"
hc add "0"
hc keybind $Mod-1               use_index 0
hc keybind $Mod-Shift-1         move_index 0
hc keybind $Mod-2               use_index 1
hc keybind $Mod-Shift-2         move_index 1
hc keybind $Mod-3               use_index 2
hc keybind $Mod-Shift-3         move_index 2
hc keybind $Mod-4               use_index 3
hc keybind $Mod-Shift-4         move_index 3
hc keybind $Mod-5               use_index 4
hc keybind $Mod-Shift-5         move_index 4
hc keybind $Mod-6               use_index 5
hc keybind $Mod-Shift-6         move_index 5
hc keybind $Mod-7               use_index 6
hc keybind $Mod-Shift-7         move_index 6
hc keybind $Mod-8               use_index 7
hc keybind $Mod-Shift-8         move_index 7
hc keybind $Mod-9               use_index 8
hc keybind $Mod-Shift-9         move_index 8
hc keybind $Mod-0               use_index 9
hc keybind $Mod-Shift-0         move_index 9


# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
#hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
#hc keybind $Mod-c cycle
#hc keybind $Mod-i jumpto urgent

#pulseaudio
#hc keybind XF86AudioRaiseVolume spawn /bin/sh -c 'pactl set-sink-volume @DEFAULT_SINK@ +5%' #increase sound volume
#hc keybind $Mod-u spawn /bin/sh -c 'pactl set-sink-volume @DEFAULT_SINK@ +5%' 
#hc keybind XF86AudioLowerVolume spawn /bin/sh -c 'pactl set-sink-volume @DEFAULT_SINK@ -5%' #decrease sound volume
#hc keybind $Mod-Shift-u spawn /bin/sh -c 'pactl set-sink-volume @DEFAULT_SINK@ -5%' 
#hc keybind XF86AudioMute spawn /bin/sh -c 'pactl set-sink-mute @DEFAULT_SINK@ toggle && pactl set-sink-volume @DEFAULT_SINK@ 100%'  #toggle mute
#hc keybind $Mod-m spawn /bin/sh -c 'pactl set-sink-mute @DEFAULT_SINK@ toggle' 

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule --instance=chromium --ewmhrequests=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
hlpath="${HOME}/.config/herbstluftwm"
pkill -f herbstluftwm/panel.sh
panel=$hlpath/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
